### ISSUE TITLE
min zig version

### ISSUE THREAD

**Issue by softprops** [ikskuh/zig-args#62]
What is this projects minimum supported zig version that can be depended on?

The projects declared min version is [0.12.0](https://github.com/ikskuh/zig-args/blob/0abdd6947a70e6d8cc83b66228cea614aa856206/build.zig.zon#L4)

I was able to use this with the current release version of 0.13.0 but a [recent commit](https://github.com/ikskuh/zig-args/commit/0abdd6947a70e6d8cc83b66228cea614aa856206) breaks in zig 0.13.0. 

Understandably zig stability is a moving target but would it be possible to cut a release tag which is compatible with 0.13.0 so users of this library do not have to depend on non released versions of zig?

**Comment by handdara** [comment]
Actually, i think according to [this](https://github.com/ikskuh/zig-args/commit/9617c3bb32df891e9d370f3decfef1c789d90e67) they're using zig master now. So the min version is master. I tried building with 0.12 but failed with the same error as 0.13.

**Comment by softprops** [comment]
Thanks for checking. I’m looking for a reliable arg parsing library which has support for a tagged release that supports the release version of zig, currently 0.13.0 


I like what you have going here but would love to see support for release versions of zig.

**Comment by ikskuh** [comment]
It kinda supports tagged releases, i just always forget to cut tags or branches. I sadly don't have much time on my hands right now, otherwise i'd just do a quick search on what's the last 0.13 version

**Comment by ikskuh** [comment]
Fixed in 236bccf4cc7871aef5c48fc102218ecf8baa48dd
